### ISSUE TITLE
Works great entering a directory, but errors when leaving a directory

### ISSUE THREAD

**Issue by Arro** [nakulj/auto-venv#1]
See screenshot: 

<img width="1040" alt="Screenshot 2023-04-12 at 9 25 37 AM" src="https://user-images.githubusercontent.com/180387/231521415-b213e479-079e-46d8-824e-18f1cd632f6c.png">

**Comment by nakulj** [comment]
See https://github.com/python/cpython/issues/93858.

Is this in a child process? How did you create the virtual environment, using venv or virtualenv? What version of python? What version of fish?

**Comment by Arro** [comment]
It's ok.   I'm going to close this.
